#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100

#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/jtsys?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false
  task:
    execution:
      pool:
        core-size: 5
        max-size: 16
        queue-capacity: 100
        keep-alive: 30
        allow-core-thread-timeout: false
      thread-name-prefix: spring.async.task-

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
  type-aliases-package: com.dongba.sys.entity

#lOG
logging:
  level:
    com.dongba: DEBUG
  file:
    path: log
    
#page
page.config:
  pageSize: 10
